server:
  port: 8081

spring:
  application:
    name: catalog-service
  data:
    mongodb:
      # Using environment variables for sensitive connection tokens
      uri: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/${MONGODB_DATABASE:auction_catalog}?authSource=admin